const ABC_TO_PITCH: Record<string, string> = {
  C: 'C4',
  '^C': 'C#4',
  _D: 'C#4',
  D: 'D4',
  '^D': 'D#4',
  _E: 'D#4',
  E: 'E4',
  F: 'F4',
  '^F': 'F#4',
  _G: 'F#4',
  G: 'G4',
  '^G': 'G#4',
  _A: 'G#4',
  A: 'A4',
  '^A': 'A#4',
  _B: 'A#4',
  B: 'B4',
  c: 'C5',
  '^c': 'C#5',
  _d: 'C#5',
  d: 'D5',
  '^d': 'D#5',
  _e: 'D#5',
  e: 'E5',
  f: 'F5',
  '^f': 'F#5',
  _g: 'F#5',
  g: 'G5',
  '^g': 'G#5',
  _a: 'G#5',
  a: 'A5',
  '^a': 'A#5',
  _b: 'A#5',
  b: 'B5',
  "c'": 'C6',
  "^c'": 'C#6',
  "_d'": 'C#6',
  "d'": 'D6',
};

export const getPitch = (abcPitch: string) => ABC_TO_PITCH[abcPitch];
